import json
from pathlib import Path
from unittest.mock import patch

from backend.models import Asset, Artifact, Chunk, Scene, Project, Premise, Channel, Job, serialize
from backend.media import render_inputs_hash
from backend.project_storage import project_path
from backend.workflow import settings_for
from backend.resource_cleanup import recover_final_moves
from backend.project_storage import write_json


def finished(client, project, tmp_path, monkeypatch):
    root=client.app.state.root
    downloads=tmp_path/'Downloads';downloads.mkdir()
    monkeypatch.setattr('backend.media_automation.downloads_root',lambda:downloads)
    folder=project_path(root,project['id'])
    image=folder/'images/scene_001.png';image.write_bytes(b'generated image')
    audio=folder/'audio/tts_001.wav';audio.write_bytes(b'generated audio')
    final=folder/'render/v1/run/final_video.mp4';final.parent.mkdir(parents=True);final.write_bytes(b'final video must remain byte identical')
    cache=final.parent/'final_audio.wav';cache.write_bytes(b'intermediate audio')
    exported=root/'exports'/f"{project['id']}-project-v1.zip";exported.write_bytes(b'old export')
    external=downloads/project['title'];external.mkdir()
    original=external/'scene_001.png';original.write_bytes(b'generated image')
    keep=external/'personal-notes.txt';keep.write_bytes(b'not generated by the app')
    downloaded_final=external/'final_video.mp4';downloaded_final.write_bytes(final.read_bytes())
    with client.app.state.database.session() as db:
        p=db.get(Project,project['id']);p.locked=True;p.story_version=1;p.draft='The door remembered my name.';p.stage='READY';p.publish={'final_reviewed':True}
        idea=Premise(project_id=p.id,title=p.title);db.add(idea);db.flush();p.selected_premise_id=idea.id
        a=Asset(project_id=p.id,name='scene_001.png',path=str(image.relative_to(root)),kind='image',size=image.stat().st_size,sha256='image-hash',story_version=1,metadata_json={'download_path':str(original),'browser_download_id':1})
        b=Asset(project_id=p.id,name='tts_001.wav',path=str(audio.relative_to(root)),kind='audio',size=audio.stat().st_size,duration=10.0,sha256='audio-hash',story_version=1,metadata_json={'has_audio':True})
        db.add_all([a,b]);db.flush()
        c=Chunk(project_id=p.id,story_version=1,number=1,text=p.draft,word_count=5,real_duration=10.0,estimated_duration=10.0,asset_id=b.id,status='ATTACHED')
        s=Scene(project_id=p.id,story_version=1,number=1,end_word=5,duration=10.0,asset_id=a.id,status='ATTACHED')
        db.add_all([c,s]);db.commit();db.expire_all()
        p=db.get(Project,project['id'])
        rows=[[serialize(row) for row in db.query(model).filter_by(project_id=p.id)] for model in (Chunk,Scene,Asset)]
        content={'story_version':1,'status':'READY','file':str(final.relative_to(root)),'checks':{'video_present':True},'warnings':[],
                 'inputs_hash':render_inputs_hash(serialize(p),*rows,settings_for(db,db.get(Channel,p.channel_id)))}
        db.add(Artifact(project_id=p.id,kind='render_report',story_version=1,content=content));db.commit()
    return {'folder':folder,'image':image,'audio':audio,'final':final,'export':exported,'original':original,'keep':keep,'downloaded_final':downloaded_final}


def preview(client, project):
    response=client.get('/api/projects/'+project['id']+'/resources/cleanup-preview')
    assert response.status_code==200,response.text
    return response.json()


def clean(client, project, report):
    return client.post('/api/projects/'+project['id']+'/resources/cleanup',json={'confirmation':report['confirmation']})


def test_cleanup_retains_identical_final_story_reuse_and_download(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    before=client.get('/api/projects/'+project['id']).json()
    assert before['premise_reuse']['ready'], before['premise_reuse']
    expected=files['final'].read_bytes()
    report=preview(client,project)
    assert not report['blocked'] and report['was_current']
    assert any(f['path']==str(files['original']) for f in report['files'])
    result=clean(client,project,report)
    assert result.status_code==200,result.text
    final=Path(result.json()['final'])
    assert final==files['folder']/'final_video.mp4' and final.read_bytes()==expected
    assert not files['image'].exists() and not files['audio'].exists() and not files['export'].exists() and not files['original'].exists()
    assert files['keep'].is_file() and files['downloaded_final'].read_bytes()==expected
    assert [p for p in files['folder'].rglob('*') if p.is_file()]==[final]
    detail=client.get('/api/projects/'+project['id']).json()
    assert detail['draft']==before['draft'] and detail['locked'] and detail['premise_reuse']['ready']
    assert detail['assets']==[] and detail['chunks'][0]['asset_id'] is None and detail['chunks'][0]['real_duration'] is None
    assert detail['next']['action_kind']=='archived_resources'
    assert client.get('/api/projects/'+project['id']+'/download/final_video.mp4').content==expected
    downloaded=client.post('/api/projects/'+project['id']+'/download-final').json()
    assert downloaded['saved'] and Path(downloaded['path']).read_bytes()==expected
    assert [p for p in files['folder'].rglob('*') if p.is_file()]==[final]
    assert client.post('/api/projects/'+project['id']+'/pipeline').json()['action_kind']=='archived_resources'
    assert client.post('/api/jobs',json={'kind':'tts_context','project_id':project['id']}).status_code==422
    assert client.post('/api/projects/'+project['id']+'/resources/resume').json()['resumed']
    assert 'resource_cleanup' not in client.get('/api/projects/'+project['id']).json()['settings']


def test_preview_change_or_active_job_cannot_delete(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    report=preview(client,project);files['image'].write_bytes(b'changed')
    assert clean(client,project,report).status_code==409 and files['final'].is_file() and files['image'].is_file()
    with client.app.state.database.session() as db:db.add(Job(project_id=project['id'],kind='render',status='running'));db.commit()
    report=preview(client,project)
    assert report['blocked'] and clean(client,project,report).status_code==409
    assert files['audio'].is_file()


def test_no_final_or_empty_final_never_deletes_resources(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    files['final'].write_bytes(b'')
    report=preview(client,project)
    assert report['blocked'] and clean(client,project,report).status_code==409
    assert files['image'].is_file() and files['audio'].is_file()


def test_shared_files_and_untracked_system_files_are_preserved(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    other=client.post('/api/projects',json={'channel_id':project['channel_id'],'title':'Other story'}).json()
    with client.app.state.database.session() as db:
        db.add(Asset(project_id=other['id'],path=str(files['image'].relative_to(client.app.state.root)),kind='image'))
        db.commit()
    report=preview(client,project)
    assert not any(f['path']==str(files['image']) for f in report['files'])
    assert clean(client,project,report).status_code==200
    assert files['image'].is_file() and files['keep'].is_file()
    assert client.get('/api/projects/'+other['id']).status_code==200


def test_final_shared_with_another_project_is_not_moved(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    other=client.post('/api/projects',json={'channel_id':project['channel_id'],'title':'Shared final'}).json()
    with client.app.state.database.session() as db:
        db.add(Asset(project_id=other['id'],path=str(files['final'].relative_to(client.app.state.root)),kind='video'))
        db.commit()
    result=clean(client,project,preview(client,project))
    assert result.status_code==200 and Path(result.json()['final'])==files['final']
    assert files['final'].read_bytes()==b'final video must remain byte identical'


def test_locked_file_reports_partial_cleanup_and_retry(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    unlink=Path.unlink
    def locked(path,*args,**kwargs):
        if path==files['original']:raise PermissionError('File is in use')
        return unlink(path,*args,**kwargs)
    with patch.object(Path,'unlink',locked):
        response=clean(client,project,preview(client,project))
    assert response.status_code==200 and response.json()['status']=='partial'
    assert response.json()['failed_files'][0]['path']==str(files['original'])
    assert files['original'].is_file()
    response=clean(client,project,preview(client,project))
    assert response.status_code==200 and response.json()['cleaned'] and not files['original'].exists()
    reuse = client.get('/api/projects/'+project['id']).json()['premise_reuse']
    assert reuse['ready'], reuse


def test_owned_capcut_copy_is_cleaned_but_wrong_manifest_is_preserved(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    owned=tmp_path/'CapCut'/'Owned';foreign=tmp_path/'CapCut'/'Foreign'
    for directory,id in ((owned,project['id']),(foreign,'other-project')):
        directory.mkdir(parents=True);(directory/'media').mkdir();(directory/'media/clip.mp4').write_bytes(b'capcut media')
        manifest={'format':'storyforge-capcut','project_id':id,'draft_id':'draft-123','folder':str(directory)}
        (directory/'storyforge_export.json').write_text(json.dumps(manifest),encoding='utf-8')
        with client.app.state.database.session() as db:
            db.add(Artifact(project_id=project['id'],kind='capcut_export',content={**manifest,'project_id':project['id']}));db.commit()
    report=preview(client,project)
    assert any(f['scope']=='CapCut' for f in report['files'])
    assert clean(client,project,report).status_code==200
    assert not owned.exists() and (foreign/'media/clip.mp4').is_file()


def test_changed_final_or_render_options_do_not_unlock_new_premise(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    result=clean(client,project,preview(client,project)).json()
    final=Path(result['final']);final.write_bytes(b'a different video')
    assert not client.get('/api/projects/'+project['id']).json()['premise_reuse']['ready']


def test_interrupted_final_move_restores_the_original_reference(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    root=client.app.state.root
    target=files['folder']/'final_video.mp4'
    signature=files['final'].stat()
    with client.app.state.database.session() as db:
        render=db.query(Artifact).filter_by(kind='render_report').one()
        report_id=render.id
    journal=root/'projects'/('.storyforge-final-move-'+project['id']+'.json')
    write_json(journal,{'project_id':project['id'],'report_id':report_id,
        'source':str(files['final'].relative_to(root)),'target':str(target.relative_to(root)),
        'signature':[signature.st_size,signature.st_mtime_ns,signature.st_ino]})
    files['final'].rename(target)
    recover_final_moves(client.app.state.database,root)
    assert files['final'].read_bytes()==b'final video must remain byte identical'
    assert not target.exists() and not journal.exists()
    assert client.get('/api/projects/'+project['id']+'/download/final_video.mp4').status_code==200


def test_active_title_change_leaves_title_and_paths_unchanged(client,project,tmp_path,monkeypatch):
    files=finished(client,project,tmp_path,monkeypatch)
    with client.app.state.database.session() as db:
        db.add(Job(project_id=project['id'],kind='render',status='running'));db.commit()
    result=client.patch('/api/projects/'+project['id'],json={'title':'A New Story Name'})
    assert result.status_code==422
    assert client.get('/api/projects/'+project['id']).json()['title']==project['title']
    assert files['final'].is_file()
