import {test,expect} from '@playwright/test';
import {deflateSync} from 'node:zlib';
function samplePng(){
  const crc=(b:Buffer)=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0};
  const chunk=(type:string,data:Buffer)=>{const b=Buffer.concat([Buffer.from(type),data]),size=Buffer.alloc(4),checksum=Buffer.alloc(4);size.writeUInt32BE(data.length);checksum.writeUInt32BE(crc(b));return Buffer.concat([size,b,checksum])};
  const header=Buffer.alloc(13);header.writeUInt32BE(1,0);header.writeUInt32BE(1,4);header[8]=8;header[9]=2;
  return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(Buffer.from([0,40,80,120]))),chunk('IEND',Buffer.alloc(0))]);
}
test('channel, duration wizard, pipeline checkpoint, persistence and asset mapping',async({page,request})=>{
  const token=(await (await request.get('/api/session')).json()).token;
  await request.patch('/api/settings',{headers:{'X-StoryForge-Token':token},data:{pipeline_mode:'auto'}});
  const title='Browser test '+Date.now();
  await page.goto('/');
  await page.getByRole('button',{name:'New channel',exact:true}).click();
  await page.getByLabel('Channel name').fill(title);
  await page.getByLabel('Primary niche').fill('Mystery');
  await page.getByRole('dialog').getByRole('button',{name:'Create channel',exact:true}).click();
  await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'New project',exact:true}).first().click();
  await page.getByLabel('Project title').fill('The browser-tested signal');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('button',{name:'5 min',exact:true}).click();
  await expect(page.getByText('750',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('button',{name:'Create project',exact:true}).click();
  await expect(page.getByRole('heading',{name:'The browser-tested signal',level:1})).toBeVisible();
  const url=page.url();
  await page.reload();
  await expect(page.getByRole('heading',{name:'The browser-tested signal',level:1})).toBeVisible();
  await page.getByRole('button',{name:'Continue pipeline',exact:true}).click();
  await page.locator('.studio-nav').getByRole('link',{name:'Premises',exact:true}).click();
  await expect(page.locator('.premise-card')).toHaveCount(10,{timeout:30000});
  await expect(page.getByRole('button',{name:'View mini-test'}).first()).toBeEnabled();
  await page.getByRole('button',{name:'Choose',exact:true}).first().click();
  await page.getByRole('button',{name:'Continue pipeline',exact:true}).click();
  await page.locator('.studio-nav').getByRole('link',{name:'Story lock',exact:true}).click();
  await expect(page.getByRole('button',{name:'Approve Story Lock',exact:true})).toBeEnabled({timeout:30000});
  await page.getByRole('button',{name:'Approve Story Lock',exact:true}).click();
  await expect(page.getByRole('button',{name:/Locked v/})).toBeVisible();
  await page.locator('.studio-nav').getByRole('link',{name:'Story audit',exact:false}).click();
  await expect(page.getByRole('button',{name:'INV-001',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'INV-001',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Evidence',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close dialog'}).click();
  await page.locator('.studio-nav').getByRole('link',{name:'Visual director',exact:true}).click();
  await page.getByRole('button',{name:'Create visual plan',exact:true}).click();
  await expect(page.locator('.visual-card')).toHaveCount(8,{timeout:15000});
  await page.locator('.studio-nav').getByRole('link',{name:'Assets',exact:true}).click();
  await expect(page.getByText('Drop your audio, images and video here')).toBeVisible();
  await page.locator('.dropzone input').setInputFiles({name:'scene_001.png',mimeType:'image/png',buffer:samplePng()});
  await expect(page.locator('.asset-card')).toHaveCount(1);
  await page.getByRole('button',{name:'Map asset'}).click();
  await page.getByLabel('Production target').selectOption({label:'Visual scene 1'});
  await page.getByLabel('Use as fallback for a video scene').check();
  await page.getByRole('button',{name:'Save mapping'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth',390);
  await expect(page.locator('.sidebar')).toBeHidden();
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await expect(page.locator('.sidebar')).toBeVisible();
  await page.getByRole('button',{name:'Close navigation'}).click();
  await expect(page.locator('.sidebar')).toBeHidden();
  await page.getByRole('button',{name:'Toggle navigation'}).click();
  await page.keyboard.press('Escape');
  await expect(page.locator('.sidebar')).toBeHidden();
  await expect(page.getByRole('heading',{level:1})).toBeInViewport();
  await page.screenshot({path:'../.runtime/mobile-project.png',fullPage:true,animations:'disabled'});
});
test('demo channel manager renders without page errors',async({page,request})=>{
  const token=(await (await request.get('/api/session')).json()).token;
  await request.post('/api/demo',{headers:{'X-StoryForge-Token':token}});
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/#/channels');
  await expect(page.getByRole('heading',{name:'Every channel. A world of its own.'})).toBeVisible();
  await expect(page.locator('.channel-card .demo-tag')).toHaveCount(3);
  await page.screenshot({path:'../.runtime/channel-manager.png',fullPage:true});
  expect(errors).toEqual([]);
});
